# ! DO NOT TOUCH !
#UNDER THIS : DO NOT TOUCH

Border:
  Startx:
  Starty:
  Endx:
  Endy:
  time: # (Start Time in ticks )

Teleport:
  world: "world"
  x: 1000
  z: 1000
  food: true
  food-stack: 64

events:
  Exposed:
    chances: 0
  LGAlone:
    chances: 0
  Trouple:
    chances : 0
  Rumeurs:
    chances: 0

modules:
  CutClean:
    state: disabled
  Smelting:
    state: disabled
  ChancesUp:
    state: disabled
  PveResistance:
    state: disabled
  DiamondLimit:
    state: disabled
  FinalHeal:
    state: disabled

roles:
  villager:
    total: 0


vote:



players:
# uuid:
#  role: nom
#  couple: boolean